//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DHubCRM.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DHubCRM.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _04f70de7_3ff5_4caf_9710_9b13ac320480 {
            get {
                object obj = ResourceManager.GetObject("04f70de7-3ff5-4caf-9710-9b13ac320480", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _20b89de1_72ca_40cf_8b64_4fea15714ff9 {
            get {
                object obj = ResourceManager.GetObject("20b89de1-72ca-40cf-8b64-4fea15714ff9", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _3426c95e_93d2_4aa7_b301_0c9b7cef9523 {
            get {
                object obj = ResourceManager.GetObject("3426c95e-93d2-4aa7-b301-0c9b7cef9523", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _3426c95e_93d2_4aa7_b301_0c9b7cef95231 {
            get {
                object obj = ResourceManager.GetObject("3426c95e-93d2-4aa7-b301-0c9b7cef95231", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _3c25af53_b2b4_4e04_89c2_94c9a9e477b5 {
            get {
                object obj = ResourceManager.GetObject("3c25af53-b2b4-4e04-89c2-94c9a9e477b5", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _3c25af53_b2b4_4e04_89c2_94c9a9e477b51 {
            get {
                object obj = ResourceManager.GetObject("3c25af53-b2b4-4e04-89c2-94c9a9e477b51", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _57b93425_6ff7_417e_961f_32864bb53a97 {
            get {
                object obj = ResourceManager.GetObject("57b93425-6ff7-417e-961f-32864bb53a97", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _588a64eed06f6719692a2d12 {
            get {
                object obj = ResourceManager.GetObject("588a64eed06f6719692a2d12", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _5b51bcb32e9dd81b10d00a3a_white_email_icon {
            get {
                object obj = ResourceManager.GetObject("5b51bcb32e9dd81b10d00a3a_white-email-icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _5c40b35d42d68e15747f09fa_mail2 {
            get {
                object obj = ResourceManager.GetObject("5c40b35d42d68e15747f09fa_mail2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _88_882904_mermaiden_crystal_dress_up_game_white_x_icon {
            get {
                object obj = ResourceManager.GetObject("88-882904_mermaiden-crystal-dress-up-game-white-x-icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _9f835b71_812e_45fb_b98e_21f109f84e8b {
            get {
                object obj = ResourceManager.GetObject("9f835b71-812e-45fb-b98e-21f109f84e8b", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _9f835b71_812e_45fb_b98e_21f109f84e8b1 {
            get {
                object obj = ResourceManager.GetObject("9f835b71-812e-45fb-b98e-21f109f84e8b1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _9f835b71_812e_45fb_b98e_21f109f84e8b2 {
            get {
                object obj = ResourceManager.GetObject("9f835b71-812e-45fb-b98e-21f109f84e8b2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _9f835b71_812e_45fb_b98e_21f109f84e8b3 {
            get {
                object obj = ResourceManager.GetObject("9f835b71-812e-45fb-b98e-21f109f84e8b3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap background {
            get {
                object obj = ResourceManager.GetObject("background", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap banner_down_arrow_link_big_ID_bf7f593a_3226_441e_e437_4b692c316c2b {
            get {
                object obj = ResourceManager.GetObject("banner_down_arrow_link_big-ID-bf7f593a-3226-441e-e437-4b692c316c2b", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap banner_down_arrow_link_big_ID_bf7f593a_3226_441e_e437_4b692c316c2b__1_ {
            get {
                object obj = ResourceManager.GetObject("banner_down_arrow_link_big-ID-bf7f593a-3226-441e-e437-4b692c316c2b (1)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap c65ef334_b5ac_4430_be5d_f5ba2c91a733 {
            get {
                object obj = ResourceManager.GetObject("c65ef334-b5ac-4430-be5d-f5ba2c91a733", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Calendar_Icon_White_svg {
            get {
                object obj = ResourceManager.GetObject("Calendar_Icon_White.svg", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap calendar_sign_white_icon_vector_15479135 {
            get {
                object obj = ResourceManager.GetObject("calendar-sign-white-icon-vector-15479135", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap chapter4__1_ {
            get {
                object obj = ResourceManager.GetObject("chapter4 (1)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap d9597e3e_2dec_4f3c_a8e8_ae2f91c6affa {
            get {
                object obj = ResourceManager.GetObject("d9597e3e-2dec-4f3c-a8e8-ae2f91c6affa", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap dc41c199_afe8_4655_99cf_b4fa74dabde9 {
            get {
                object obj = ResourceManager.GetObject("dc41c199-afe8-4655-99cf-b4fa74dabde9", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap dc4ab285_1a3b_45b8_a2d3_9452d60d1440 {
            get {
                object obj = ResourceManager.GetObject("dc4ab285-1a3b-45b8-a2d3-9452d60d1440", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap dfba49ab_f054_4030_9522_85f0e36c6682 {
            get {
                object obj = ResourceManager.GetObject("dfba49ab-f054-4030-9522-85f0e36c6682", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap f089e33d_2bdf_48d7_8053_2d48f281a66b {
            get {
                object obj = ResourceManager.GetObject("f089e33d-2bdf-48d7-8053-2d48f281a66b", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap f089e33d_2bdf_48d7_8053_2d48f281a66b1 {
            get {
                object obj = ResourceManager.GetObject("f089e33d-2bdf-48d7-8053-2d48f281a66b1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap fae19725_c765_4a96_b04a_3bf41749d259 {
            get {
                object obj = ResourceManager.GetObject("fae19725-c765-4a96-b04a-3bf41749d259", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap grey_down_arrow_icon_png_1 {
            get {
                object obj = ResourceManager.GetObject("grey-down-arrow-icon-png-1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap House {
            get {
                object obj = ResourceManager.GetObject("House", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icon_downarrow {
            get {
                object obj = ResourceManager.GetObject("icon_downarrow", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icondownarrowchevron {
            get {
                object obj = ResourceManager.GetObject("icondownarrowchevron", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icondownarrowchevron1 {
            get {
                object obj = ResourceManager.GetObject("icondownarrowchevron1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap kisspng_desktop_wallpaper_computer_icons_email_white_icon_5b4804abb4daf3_4105242615314464437408 {
            get {
                object obj = ResourceManager.GetObject("kisspng-desktop-wallpaper-computer-icons-email-white-icon-5b4804abb4daf3.41052426" +
                        "15314464437408", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Material_icons_01_12_512 {
            get {
                object obj = ResourceManager.GetObject("Material_icons-01-12-512", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap navicon {
            get {
                object obj = ResourceManager.GetObject("navicon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap navicon1 {
            get {
                object obj = ResourceManager.GetObject("navicon1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Status_mail_attachment_icon {
            get {
                object obj = ResourceManager.GetObject("Status-mail-attachment-icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap threelines {
            get {
                object obj = ResourceManager.GetObject("threelines", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap white_down_arrow_png_2_300x300 {
            get {
                object obj = ResourceManager.GetObject("white-down-arrow-png-2-300x300", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap x_close_icon_white {
            get {
                object obj = ResourceManager.GetObject("x-close-icon-white", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
